/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PanierRouteImport } from './routes/panier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/menu': typeof MenuRoute
  '/panier': typeof PanierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/menu': typeof MenuRoute
  '/panier': typeof PanierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/menu': typeof MenuRoute
  '/panier': typeof PanierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caisse' | '/menu' | '/panier'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caisse' | '/menu' | '/panier'
  id: '__root__' | '/' | '/caisse' | '/menu' | '/panier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaisseRoute: typeof CaisseRoute
  MenuRoute: typeof MenuRoute
  PanierRoute: typeof PanierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaisseRoute: CaisseRoute,
  MenuRoute: MenuRoute,
  PanierRoute: PanierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
